### ISSUE TITLE
Why `import * as React` instead of `import React`?

### ISSUE THREAD

**Issue by akx** [ngfk/poi-preset-react-typescript#1]
Hey,

I wanted to try React + TypeScript out and found this repo :)

Out of habit with regular JavaScript/JSX React projects, I tried `import React from 'react';` in my app component file, and it didn't work (`React` is `undefined`).
Is this a TypeScript thing, or is it related to this configuration?

I'd like to use the more concise `import React from 'react';`, if that's possible.

**Comment by ngfk** [comment]
Sorry for the late reply, for some reason I was not watching this project.

React doesn't actually use the ES6 way of defining default imports. However with Babel the default behaviour is that if you use an ES6 import to get a CommonJS module the `module.export` value will be used as the default export.

You can get the same behaviour in typescript if you set the `allowSyntheticDefaultImports` option to `true` in your tsconfig file.

**Comment by akx** [comment]
Cool. Thanks for the explanation!

–– And of course also thanks for the project! :) It's working great.
